# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6eb09ee291faa4156e82374047f43f5b7d107a093f346b7adce4781d445d05c92d9b458db66cd66b690c1452b9bc459bca88e0500742bba2495683ca6f2c4895

test:
  secret_key_base: 6acf6d2723157b84543b9e9f0690f55e2b231cc3e513f622cfe15e53e2cc65b308c81f191329fe215b423678931443f80cfe2072b98d37dca89a5d14f1e6a799

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
